SonarSource/sonar-plugin-api

build.gradle, gradle.properties
Adjusting version setup to other projects, though it is still not showing SNAPSHOT versions on PRs
=> Fix SNAPSHOT versioning

sonar-plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, sonar-plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, sonar-plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java
[PLUGINAPI-19](https://jira.sonarsource.com/browse/PLUGINAPI-19)
=> PLUGINAPI-19 support OWASP ASVS

gradle.properties
* 469e655 REL-2312 Prepare for next version.
=> REL-2312 Prepare for next version

README.md, docs/optimize-sensors.md
=> Document APIs used for optimizing sensors

sonar-plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/Issue.java, sonar-plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewIssue.java
=> PLUGINAPI-25 Return flow description and type

.cirrus.star, .cirrus.yml
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create a new thread in the forum "Suggest new features".
With that in mind, if you would like to submit a code contribution, make sure that you adhere to the following guidelines and all tests are passing:
Please explain your motives to contribute this change: what problem you are trying to fix, what improvement you are trying to make
Use the following formatting style: SonarSource/sonar-developer-toolset
Provide a unit test for any code you changed
If there is a JIRA ticket …
=> BUILD-2277 Migrate to CirrusCI on AWS

plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/AdHocRule.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/NewAdHocRule.java, plugin-api/src/main/java/org/sonar/api/ce/measure/Issue.java, plugin-api/src/main/java/org/sonar/api/ce/measure/test/TestIssue.java, plugin-api/src/main/java/org/sonar/api/code/CharacteristicsCategory.java, plugin-api/src/main/java/org/sonar/api/code/CodeCharacteristic.java, plugin-api/src/main/java/org/sonar/api/rules/RuleType.java, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultRule.java, plugin-api/src/test/java/org/sonar/api/ce/measure/test/TestIssueTest.java, plugin-api/src/test/java/org/sonar/api/ce/measure/test/TestMeasureComputerContextTest.java, plugin-api/src/test/java/org/sonar/api/code/CodeCharacteristicTest.java, plugin-api/src/test/java/org/sonar/api/server/impl/RulesDefinitionContextTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultRuleTest.java
=> Clean Code Taxonomy, baby step

plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRepository.java, plugin-api/src/test/java/org/sonar/api/server/impl/RulesDefinitionContextTest.java
=> PLUGINAPI-14 Rename default repository from "SonarQube" to "Sonar"

gradle.properties
=> [NO JIRA] Change version to 10.0-SNAPSHOT

.github/CODEOWNERS
=> Add Leo to codeowners

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/ExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/AdHocRule.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/NewAdHocRule.java, plugin-api/src/main/java/org/sonar/api/rules/CleanCodeAttribute.java, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultRule.java, plugin-api/src/test/java/org/sonar/api/rules/CleanCodeAttributeTest.java, plugin-api/src/test/java/org/sonar/api/server/impl/RulesDefinitionContextTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultRuleTest.java
=> DRAFT - Feature/bca/mmf 3128 issues pages uses clean code taxonomy

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/batch/rule/Severity.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/ExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/Issue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/AdHocRule.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/NewAdHocRule.java, plugin-api/src/main/java/org/sonar/api/ce/measure/Issue.java, plugin-api/src/main/java/org/sonar/api/issue/Issue.java, plugin-api/src/main/java/org/sonar/api/issue/impact/Severity.java, plugin-api/src/main/java/org/sonar/api/issue/impact/SoftwareQuality.java, plugin-api/src/main/java/org/sonar/api/rule/Severity.java, plugin-api/src/main/java/org/sonar/api/rules/CleanCodeAttribute.java, plugin-api/src/main/java/org/sonar/api/rules/CleanCodeAttributeCategory.java, plugin-api/src/main/java/org/sonar/api/rules/RuleType.java, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultRule.java, plugin-api/src/test/java/org/sonar/api/rules/CleanCodeAttributeTest.java, plugin-api/src/test/java/org/sonar/api/server/impl/RulesDefinitionContextTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultRuleTest.java, test-fixtures/src/main/java/org/sonar/api/testfixtures/measure/TestIssue.java, test-fixtures/src/test/java/org/sonar/api/testfixtures/measure/TestIssueTest.java, test-fixtures/src/test/java/org/sonar/api/testfixtures/measure/TestMeasureComputerContextTest.java
=> New Clean Code Taxonomy

plugin-api/src/main/java/org/sonar/api/issue/impact/package-info.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java
=> NO-JIRA Fix code smell

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/rules/CleanCodeAttribute.java, plugin-api/src/main/java/org/sonar/api/server/rule/RuleTagsToTypeConverter.java, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/test/java/org/sonar/api/rules/CleanCodeAttributeTest.java
=> PLUGINAPI-63 Update @CheckForNull on type and severity for rule and add default clean code attribute to enum

plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/ExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewExternalIssue.java
…dd default clean code attribute to enum
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our roadmap and expectations. Therefore, we typically only accept minor cosmetic changes and typo fixes. If you would like to see a new feature, please create …
=> PLUGINAPI-64 Mark cleanCodeAttribute and impacts as @Beta in externalIssue

plugin-api/src/main/java/org/sonar/api/server/rule/internal/ImpactMapper.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/ImpactMapperTest.java
=> PLUGINAPI-65 Change order of selection for best impact for backmapping

.github/PULL_REQUEST_TEMPLATE.md
=> Update test name convention in pull request template

CHANGELOG.md, plugin-api/build.gradle, plugin-api/src/main/java/org/sonar/api/PropertyType.java, plugin-api/src/main/java/org/sonar/api/config/EmailSettings.java, plugin-api/src/main/java/org/sonar/api/config/PropertyDefinition.java, plugin-api/src/test/java/org/sonar/api/config/PropertyDefinitionTest.java, settings.gradle
=> PLUGINAPI-68 Introduce email property type

README.md
Verify [here](https://github.com/SonarSource/sonarcloud-core/blob/master/build.gradle#L355) the version currently used at SonatCloud.
=> [NO-JIRA] Update SonarCloud version

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/issue/DefaultTransitions.java, plugin-api/src/main/java/org/sonar/api/issue/Issue.java
PLUGINAPI-70
I feel like 0% code coverage here can be safely ignored.
=> PLUGINAPI-70 added new transition and resolution

plugin-api/src/test/java/org/sonar/api/issue/DefaultTransitionsTest.java, plugin-api/src/test/java/org/sonar/api/issue/IssueTest.java
I am not proud of this code, but it will kill the noise with failing QG on new code. I am open to other ideas how to fix the QG.
=> NO-JIRA fixing SonarQube quality gate on new code. Adding tests that cover interfaces.

gradle.properties
=> Prepare for next development iteration

README.md
=> Fix sonarqube compatibility matrix for sonarqube

.cirrus.yml
https://sonarsource.atlassian.net/browse/PLUGINAPI-74
=> PLUGINAPI-74 updated cirrus.yml to move away from GCP

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java
=> Introduced new metric 'pull_request_fixed_issues'

README.md
This is due to a community thread mentioning that the version here hasn't been updated in quite some time. I'll change it also on SLCORE to make developers aware that when they change the version there, they also have to change the version here!
Whoever is reviewing it here, please also review the sister [PR](https://github.com/SonarSource/sonarlint-core/pull/887). Thank you!
=> NO-JIRA: Fix version used by SonarLint

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java
=> PLUGINAPI-88 Deprecate metrics based on old status and type

gradle.properties
=> NO-JIRA Prepare for next development iteration

plugin-api/src/main/java/org/sonar/api/utils/AnnotationUtils.java
Assigned it to you @henryju as you reviewed https://github.com/SonarSource/sonar-plugin-api/pull/162 for @ericg138, and he's off
=> NOJIRA Remove unused import

.cirrus.star, .cirrus.yml, .github/workflows/releasability.yaml, .github/workflows/release.yml, README.md, build.gradle
Based on https://github.com/SonarSource/sonar-dummy-oss/tree/master
=> Update the build

.github/workflows/releasability.yaml
=> Update releasability version

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/DefaultNewRuleTest.java
=> PLUGINAPI-98 Add STIG standard support

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/issue/impact/Severity.java, plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/ImpactMapper.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/ImpactMapperTest.java
=> PLUGINAPI-100 Add new severities to impact

gradle.properties
=> Prepare next dev iteration

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/batch/rule/ActiveRule.java, plugin-api/src/main/java/org/sonar/api/batch/rule/LoadedActiveRule.java, plugin-api/src/test/java/org/sonar/api/batch/rule/ChecksTest.java, plugin-api/src/test/java/org/sonar/api/batch/rule/LoadedActiveRuleTest.java
=> PLUGINAPI-101 Add imapcts to loaded active rule

CHANGELOG.md, plugin-api/src/main/java/org/sonar/api/batch/rule/Severity.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/ExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/Issue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewExternalIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/issue/NewIssue.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/AdHocRule.java, plugin-api/src/main/java/org/sonar/api/batch/sensor/rule/NewAdHocRule.java, plugin-api/src/main/java/org/sonar/api/ce/measure/Issue.java, plugin-api/src/main/java/org/sonar/api/issue/Issue.java, plugin-api/src/main/java/org/sonar/api/measures/CoreMetrics.java, plugin-api/src/main/java/org/sonar/api/rule/Severity.java, plugin-api/src/main/java/org/sonar/api/rules/RuleType.java, plugin-api/src/main/java/org/sonar/api/server/rule/RuleTagsToTypeConverter.java, plugin-api/src/main/java/org/sonar/api/server/rule/RulesDefinition.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultNewRule.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/DefaultRule.java, plugin-api/src/main/java/org/sonar/api/server/rule/internal/ImpactMapper.java, plugin-api/src/test/java/org/sonar/api/server/rule/internal/ImpactMapperTest.java, test-fixtures/src/main/java/org/sonar/api/testfixtures/measure/TestIssue.java
=> PLUGINAPI-106 Remove deprecation on RuleType and Rule Severity

.github/workflows/release.yml
=> Enable publishing javadoc

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[PLUGINAPI-107](https://sonarsource.atlassian.net/browse/PLUGINAPI-107)
The new YML are replacing the old `synchronize-jira.yml` (if present)
Make sure the files in the PR are the same as these
[PullRequestClosed.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml)
[PullRequestCreated.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml)
[RequestReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml)
[SubmitReview.yml](https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml)
⚠️ Please make sure that `PullRequestCreated.yml` has the correct Jira project on the last …
=> PLUGINAPI-107 Add Jira integration

README.md
[PLUGINAPI-109](https://sonarsource.atlassian.net/browse/PLUGINAPI-109)
[PLUGINAPI-109]: https://sonarsource.atlassian.net/browse/PLUGINAPI-109?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLUGINAPI-109 Document compatibility with SQS 10.8

gradle.properties
[PLUGINAPI-114](https://sonarsource.atlassian.net/browse/PLUGINAPI-114)
[PLUGINAPI-114]: https://sonarsource.atlassian.net/browse/PLUGINAPI-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> PLUGINAPI-114 Prepare next release iteration

gradle.properties
[PLUGINAPI-115](https://sonarsource.atlassian.net/browse/PLUGINAPI-115)
Please be aware that we are not actively looking for feature contributions. The truth is that it's extremely difficult for someone outside SonarSource to comply with our …
=> PLUGINAPI-115 Prepare next iteration
